config/routes.rb
Rails.application.routes.draw do
  root 'darts#home'
  get 'darts_online' => 'darts#darts_online'
  get 'competitions' => 'darts#competitions'
  get 'resources' => 'darts#resources'
  get 'contacts' => 'darts#contacts'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/darts_controller.rb
class DartsController < ApplicationController

  def home
  end

  def darts_online
  end

  def competitions
  end

  def resources
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/darts_helper.rb
module DartsHelper
end

app/views/darts/competitions.html.erb
<h1>Competitions</h1>

app/views/darts/contacts.html.erb
<h1>Contact me</h1>

app/views/darts/darts_online.html.erb
<h1>Watch video here</h1>
<div id="video_frame">
</div>

app/views/darts/home.html.erb
<%= render 'layouts/main_nav' %>

app/views/darts/resources.html.erb
<h1>What and where</h1>

app/views/darts/video_online.html.erb
<h1>Watch video here</h1>

app/views/layouts/_header.html.erb
<% unless controller.action_name == 'home' %>
  <header id='mobile_nav'>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li id='title'><span><%= controller.action_name.capitalize %></span></li>
      <li id='menu'><%= link_to 'Menu', '#' %></li>
    </ul>
  </header>
<% end %>

app/views/layouts/_main_nav.html.erb
<div id="main_nav">
  <%= link_to "Apps", '#', class: 'on_white', id: 'apps_link' %>
  <%= link_to "Video", darts_online_path, class: 'on_black', id: 'videos_link' %>
  <%= link_to "Competitions", competitions_path, class: 'on_white', id: 'competitions_link' %>
  <%= link_to "Resources", resources_path, class: 'on_black', id: 'resources_link' %>
  <%= link_to "Contacts", contacts_path, class: 'on_white', id: 'my_contacts_link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Darts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller.action_name %>">
<%= render 'layouts/header' %>
<% unless controller.action_name == 'home' %>
  <%= render 'layouts/main_nav' %>
<% end %>
<main>
  <%= yield %>
</main>
</body>
</html>